Repository verdaccio/monorepo, pull requests merged in 2019-12, with the labels that each got.

#282 Enable Ts 3.7 features
  tools/babel-preset/lib/builder.js
  tools/babel-preset/package.json
  tools/eslint-config/package.json
  tools/eslint-config/rules/typescript.js
  yarn.lock
Labels: dependencies, tool

#306 fix: add new types for local storage
  core/types/index.d.ts
Labels: enhancement

#289 fix: return 404 on removePackage
  plugins/aws-s3-storage/src/s3PackageManager.ts
Labels: code review
